require("./bootstrap");
import "./theme/theme";
import ExerciseInput from "./components/ExerciseInput";
import DeleteExerciseBtn from "./components/DeleteExerciseBtn";
import AddExerciseBtn from "./components/AddExerciseBtn";
import OrderInput from "./components/OrderInput";
import CopyParameterBtn from "./components/CopyParameterBtn";
import CopyWorkoutBtn from "./components/CopyWorkoutBtn";
import TemplateCategorySelect from "./components/TemplateCategorySelect";
import AddTemplateCategoryBtn from "./components/AddTemplateCategoryBtn";
import TemplateCategoryBtn from "./components/TemplateCategoryBtn";
import FoodNameInput from "./components/FoodNameInput";
import AddFoodBtn from "./components/AddFoodBtn";
import FoodPortionSelect from "./components/FoodPortionSelect";
import FoodQuantityInput from "./components/FoodQuantityInput";
import FoodTypeSelect from "./components/FoodTypeSelect";
import FoodGroupInput from "./components/FoodGroupInput";
import DeleteFoodBtn from "./components/DeleteFoodBtn";
import AddMealBtn from "./components/AddMealBtn";
import AutoCompleteInput from "./components/AutoCompleteInput";

new AutoCompleteInput();
new AddExerciseBtn();
new DeleteExerciseBtn();
new ExerciseInput();
new OrderInput();
new CopyParameterBtn();
new CopyWorkoutBtn();
new TemplateCategorySelect();
new AddTemplateCategoryBtn();
new TemplateCategoryBtn();
//new FoodNameInput();
new AddFoodBtn();
new FoodPortionSelect();
new FoodQuantityInput();
new FoodGroupInput();
new FoodTypeSelect();
new DeleteFoodBtn();
new AddMealBtn();
